obs_osv_arkiv/archive/urls.py
from django.conf.urls import patterns, include, url
import archive.views

urlpatterns = patterns('',
    url(r'^$', archive.views.ItemListView.as_view()), 
    url(r'^node/(?P<node_pk>\d+)/$', archive.views.ItemListView.as_view(), name='node'), 
    url(r'^node/(?P<node_pk>\d+)/item/(?P<pk>\d+)$', archive.views.ItemDetailView.as_view(), name='node_and_item'), 
    url(r'^item/(?P<pk>\d+)/$', archive.views.ItemDetailView.as_view(), name='item'), 
    url(r'^search/$', archive.views.ItemSearchView.as_view(), name='item_search'), 
    url(r'^search/results/$', archive.views.ItemSearchResultView.as_view(), name='item_search_results'), 
    url(r'^country/(?P<country>.*)/$', archive.views.ItemListView.as_view(), name='country'), 
    url(r'^artist/(?P<artist>.*)/$', archive.views.ItemListView.as_view(), name='artist'), 
    url(r'^city/(?P<city>.*)/$', archive.views.ItemListView.as_view(), name='city'), 
    url(r'^keyword_autocomplete/$', 'archive.views.keyword_autocomplete'),
    url(r'^material_autocomplete/$', 'archive.views.material_autocomplete'),
    url(r'^room_autocomplete/$', 'archive.views.room_autocomplete'),
    url(r'^area_autocomplete/$', 'archive.views.area_autocomplete'),
    url(r'^location_autocomplete/$', 'archive.views.location_autocomplete'),
    url(r'^title_autocomplete/$', 'archive.views.title_autocomplete'),
    url(r'^artist_autocomplete/$', 'archive.views.artist_autocomplete'),
    url(r'^category_autocomplete/$', 'archive.views.category_autocomplete'),
    url(r'^city_autocomplete/$', 'archive.views.city_autocomplete'),
    url(r'^country_autocomplete/$', 'archive.views.country_autocomplete'),
    url(r'^materials_autocomplete/$', 'archive.views.materials_autocomplete'),
    url(r'^media_details/$', 'archive.views.image_details'),
    url(r'^search_autocomplete/$', 'archive.views.search_autocomplete'),
    url(r'^filter_media/$', 'archive.views.filter_media', name='find_media'),
    url(r'^copyright/$', 'archive.views.copyright'),
)

urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'obs_osv_arkiv.views.home', name='home'),
    # url(r'^obs_osv_arkiv/', include('obs_osv_arkiv.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url('', include('archive.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

archive/models.py
#coding=utf-8

from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User
from os.path import split, splitext
from django.conf import settings
from easy_thumbnails.files import get_thumbnailer

import os
import settings


class ItemHistory(models.Model):
	action_time = models.DateTimeField(_('action time'), auto_now=True) 
	user = models.ForeignKey(User)
	item = models.ForeignKey('Item')
	field = models.CharField(max_length=50, verbose_name=_("field"))
	value = models.CharField(max_length=200, verbose_name=_("value"))

class Category(MPTTModel):
	name = models.CharField(max_length=50, verbose_name=_("name"))
	parent = TreeForeignKey('self', null=True, blank=True, related_name='children', verbose_name=_("parent"))
	description = models.TextField(null=True, blank=True)
	
	class Meta:
		unique_together = (("name", "parent"), )
		verbose_name = _("category")
		verbose_name_plural = _("categories")
	
	def __unicode__(self):
		category_path = [c.name for c in self.get_ancestors()]
		category_path.append(self.name)
		return('>'.join(category_path))

class File(models.Model):
	file = models.FileField(upload_to='media', verbose_name=_("file"))
	media = models.ForeignKey('Media')
	order = models.IntegerField(blank=True, null=True)	
	
	class Meta:
		verbose_name = _("file")
		verbose_name_plural = _("files")
	
	def content_type(self):
		import mimetypes
		type = mimetypes.guess_type(self.file.name)[0]
		if type is None: #Should include a test for webm
			type = 'video/webm'
		return(type)
	
	def __unicode__(self):
		return(self.file.name)
	
class Media(models.Model):
	MEDIA_TYPE_IMAGE = 'Picture'
	MEDIA_TYPE_MOVIE = 'Movie'
	MEDIA_TYPE_SOUND = 'Sound'
	MEDIA_TYPE_TEXT = 'Text'
	MEDIA_TYPE_MISC = 'Misc'

	MEDIA_TYPES = (
		(MEDIA_TYPE_IMAGE, _("Picture")),
		(MEDIA_TYPE_MOVIE, _('Film/Animation')),
		(MEDIA_TYPE_SOUND, _('Sound')),
		(MEDIA_TYPE_TEXT, _('Text')),
		(MEDIA_TYPE_MISC, _('Other'))
	)

	ICON_COLOR_BLACK = 0
	ICON_COLOR_WHITE = 1
	ICON_COLORS = (
		(ICON_COLOR_WHITE, _("White")),
		(ICON_COLOR_BLACK, _("Black")),
	)
	
	filename = models.FileField(upload_to='media', verbose_name=_("thumbnail"), blank=True)
	media_type = models.CharField(max_length=10, choices=MEDIA_TYPES, verbose_name=_("filetype"))
	macro_zoom = models.BooleanField(default=False)
	icon_color = models.IntegerField(default=ICON_COLOR_WHITE, choices=ICON_COLORS)
	
	class Meta:
		verbose_name = _("media")
		verbose_name_plural = _("media")
	
	def icon_color_name(self):
		if self.icon_color == self.ICON_COLOR_BLACK:
			return 'black'
		return 'white'

	def thumbnail(self, width, height):
		"""
		Generate a thumbnail image of this media file, and return its URL.
		"""
		if self.filename and os.path.exists(self.filename.path):
			thumbnailer = get_thumbnailer(self.filename)
			try:
				thumb = thumbnailer.get_thumbnail({'size': (width, height)})
				thumb_url = thumb.url
				return thumb_url
			except Exception as e:
				raise e #pass

		thumb_url = settings.STATIC_URL + 'images/'
		
		if self.media_type == self.MEDIA_TYPE_IMAGE:
			thumb_url = thumb_url + 'thumb_image.jpg'
		elif self.media_type == self.MEDIA_TYPE_MOVIE:
			thumb_url = thumb_url + 'thumb_movie.jpg'
		elif self.media_type == self.MEDIA_TYPE_SOUND:
			thumb_url = thumb_url + 'thumb_audio.jpg'
		elif self.media_type == self.MEDIA_TYPE_TEXT:
			thumb_url = thumb_url + 'thumb_text.jpg'
		else:
			thumb_url = thumb_url + 'thumb_misc.jpg'
		return(thumb_url)
		
	def __unicode__(self):
		from os.path import basename
		if self.filename:
			if self.file_set.all().count() > 0:
				if self.file_set.all().count() > 2:
					return(basename(self.filename.name) + u' (' + unicode(self.file_set.all().count()) + u' ' + 'files' + ')')
				else:
					return(basename(self.filename.name) + ' (' + ', '.join([basename(f.file.name) for f in self.file_set.all()]) + ')')
			else:
				return(basename(self.filename.name))
		elif self.file_set.count() > 0:
			return(basename(self.file_set.all()[0].file.name))
		else:
			return(_('media') + u' ' + str(self.pk))

class ItemMedia(models.Model):
	item = models.ForeignKey('Item', verbose_name=_("item"))
	media = models.ForeignKey('Media', verbose_name=_("media"))
	order = models.IntegerField(verbose_name=_("order"))
	
	def __unicode__(self):
		return(self.media.__unicode__())
	
class Tag(models.Model):
	name = models.CharField(max_length=200, verbose_name=_("name"))
	description = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("description"))
	
	class Meta:
		verbose_name = _("tag")
		verbose_name_plural = _("tags")
		
	def __unicode__(self):
		return(self.name)

class Materials(models.Model):
	name = models.CharField(max_length=200)
	description = models.CharField(max_length=200, blank=True, null=True)
	
	class Meta:
		verbose_name = _("material")
		verbose_name_plural = _("materials")
	
	def __unicode__(self):
		return(self.name)

class Keywords(models.Model):
	name = models.CharField(max_length=200)
	description = models.CharField(max_length=200, blank=True, null=True)
	
	class Meta:
		verbose_name = _("keywords")
		verbose_name_plural = _("keywords")
	
	def __unicode__(self):
		return(self.name)

class Condition(models.Model):
	name = models.CharField(max_length=50)
	description = models.CharField(max_length=300)
	condition_value = models.IntegerField(max_length=3)
	
	class Meta:
		verbose_name = _("condition")
		verbose_name_plural = _("conditions")
	
	def __unicode__(self):
		return str(self.condition_value)

class Address(models.Model):
	name = models.CharField(max_length=200, verbose_name=_("name"))
	street = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("street"))
	postal_number = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("postal number"))
	postal_area = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("postal area"))
	country = models.CharField(max_length=200, blank=True, null=True, verbose_name=_("country"))
	
	class Meta:
		verbose_name = _("address")
		verbose_name_plural = _("addresses")
	
	def __unicode__(self):
		return(self.name)

class Area(models.Model):
	name = models.CharField(max_length=200, verbose_name=_("name")) 
	address = models.ForeignKey(Address, verbose_name=_("address"))
	
	class Meta:
		unique_together = (("name", "address"), )
		verbose_name = _("area/building")
		verbose_name_plural = _("areas/buildings")
	
	def __unicode__(self):
		return(self.name)

class Room(models.Model):
	name = models.CharField(max_length=200, verbose_name=_("name"))
	area = models.ForeignKey(Area, verbose_name=_("area"))
	
	class Meta:
		unique_together = (("name", "area"), )
		verbose_name = _("subarea/room")
		verbose_name_plural = _("subareas/rooms")
	
	def __unicode__(self):
		return(self.name)

class Location(models.Model):
	name = models.CharField(max_length=200, verbose_name=_("name"))
	room = models.ForeignKey(Room, verbose_name=_("room"))
	
	class Meta:
		unique_together = (("name", "room"), )
		verbose_name = _("location")
		verbose_name_plural = _("locations")
	
	def __unicode__(self):
		return(self.name)

class Item(models.Model):
	ERA_CHOICES = (
		('AD', _('AD')),
		('BC', _('BC'))
	)
	CERTAINTY_CHOICES = (
		('sure', _("sure")),
		('uncertain', _("approximate/uncertain"))
	)

	class Meta:
		verbose_name = _('Item')
		verbose_name_plural = _('Items')
	
	def header_image(self):
		return(self.itemmedia_set.order_by('order')[:1])
		
	published = models.BooleanField(verbose_name=_("published"), default=False)
	item_number = models.CharField(max_length=14, unique=True, blank=False, verbose_name=_("item number"))
	title = models.CharField(max_length=200, blank=True, verbose_name=_("title"), null=True)
	condition = models.ForeignKey(Condition, blank=True, null=True, verbose_name=_("condition"))
	condition_comment = models.TextField(verbose_name=_('condition details'), blank=True, null=True)
	dating_certainty = models.CharField(max_length=20, choices=CERTAINTY_CHOICES, verbose_name=_("certainty"), blank=True, null=True) 
	era_from = models.CharField(max_length=2, choices=ERA_CHOICES, verbose_name=_("period"), blank=True, null=True)
	date_from = models.IntegerField(verbose_name=_("from"), blank=True, null=True)
	era_to = models.CharField(max_length=2, choices=ERA_CHOICES, verbose_name=_("period"), blank=True, null=True)
	date_to = models.IntegerField(verbose_name=_("to"), blank=True, null=True)
	origin_certainty = models.CharField(max_length=20, choices=CERTAINTY_CHOICES, verbose_name=_("certainty"), blank=True, null=True) 
	origin_city = models.CharField(max_length=200, verbose_name=_("city"), blank=True, null=True)
	origin_country = models.CharField(max_length=200, verbose_name=_("country"), blank=True, null=True)
	origin_continent = models.CharField(max_length=200, verbose_name=_("continent"), blank=True, null=True)
	origin_provinience = models.TextField(verbose_name=_("provinience"), blank=True, null=True)
	artist = models.CharField(max_length=200, verbose_name=_("artist"), blank=True, null=True)
	dim_height = models.DecimalField(decimal_places=2, max_digits=9, verbose_name=_("height (cm)"), blank=True, null=True)
	dim_width = models.DecimalField(decimal_places=2, max_digits=9, verbose_name=_("width (cm)"), blank=True, null=True)
	dim_depth = models.DecimalField(decimal_places=2, max_digits=9, verbose_name=_("depth (cm)"), blank=True, null=True)
	dim_weight = models.DecimalField(decimal_places=2, max_digits=9, verbose_name=_("weight (g)"), blank=True, null=True)
	materials = models.ManyToManyField(Materials, verbose_name=_("materials/technique"), blank=True)
	keywords = models.ManyToManyField(Keywords, verbose_name=_("keywords"), blank=True)
	ref_literature = models.TextField(verbose_name=_("literature"), blank=True)	
	address = models.ForeignKey(Address, verbose_name=_("address"), blank=True, null=True)

obs_osv_arkiv/archive/forms.py
import pdb
from django import forms
from django.forms import widgets
from archive.models import Item, Condition, Tag, Location, Keywords, Materials
from archive.widgets import ManyToManyTextWidget #,KeywordWidget, MaterialWidget, 
from django.forms.util import flatatt
from django.utils.safestring import mark_safe
from django.utils.encoding import force_unicode
from itertools import chain
from django.utils.translation import ugettext as _


class ItemSearchForm(forms.Form):
    categories = forms.CharField(label=_('Category'), required=False)
    title = forms.CharField(label=_('Title'), required=False)
    artist = forms.CharField(label=_('Artist'), required=False)
    date_from = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder': _('FROM')}), label=_('Dating, from'), required=False)
    date_to = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder': _('TO')}), label=_('Dating, to'), required=False)
    origin_city = forms.CharField(widget=forms.TextInput(attrs={'placeholder': _('CITY')}), label=_('City'), required=False)
    origin_country = forms.CharField(widget=forms.TextInput(attrs={'placeholder': _('COUNTRY')}), label=_('Country'), required=False)
    materials = forms.CharField(label=_('Material/technique'), required=False)
    q = forms.CharField(label=_('Fulltext'), required=False)
    video_only = forms.BooleanField(widget=forms.CheckboxInput, label=_('Item with movies'), required=False)

class ItemAdminForm(forms.ModelForm):
    materials = forms.CharField(widget=ManyToManyTextWidget(attrs={'rows': 3, 'cls': Materials}), required=False, label=_("Materials"))
    keywords = forms.CharField(widget=ManyToManyTextWidget(attrs={'rows': 3, 'cls': Keywords}), required=False, label=_("Keywords"))

    class Meta:
        model = Item

    def clean(self):
        self.cleaned_data = super(ItemAdminForm, self).clean()
        #lookup and link materials
        materials = []
        keywords = []


        for material in self.cleaned_data['materials'].split(','):
            if len(material.strip()) > 0:
                if Materials.objects.filter(name=material.strip()).count() > 0:
                    m = Materials.objects.filter(name=material.strip())[0]
                else:
                    m = Materials(name=material.strip())
                    m.save()

                materials.append(m)

        for keyword in self.cleaned_data['keywords'].split(','):
            if len(keyword.strip()) > 0:
                if Keywords.objects.filter(name=keyword.strip()).count() > 0:
                    k = Keywords.objects.filter(name=keyword.strip())[0]
                else:
                    k = Keywords(name=keyword.strip())
                    k.save()

                keywords.append(k)

        self.cleaned_data['materials'] = materials
        self.cleaned_data['keywords'] = keywords

        return(self.cleaned_data)

archive/templates/archive/copyright.html
<!DOCTYPE HTML>
<html>
<head>
<meta charset=UTF-8>
<title>Copyright</title>

<link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans:400,400italic,700,700italic' rel='stylesheet' type='text/css' />
<link rel="stylesheet" type="text/css" href='{{STATIC_URL}}css/style.css' media='screen' />
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/jquery-ui-1.9.2.custom.min.css" />

<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<script type="text/javascript" src="{{STATIC_URL}}js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/jquery-ui-1.9.2.custom.min.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/jquery.isotope.min.js"></script>

<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1" />
</head>

<body>

<div id="page-wrap">
  
  <header>
    
    <nav id="main-nav">
    <a class="cat" href="/">tilbake</a>
    </nav>

<div id="copyright">

<p>&copy; BLAKER MEIERIS VENNER & GUTTORM GUTTORMSGAARD</p>
<p>Henvendelser til GUTTORMSGAARDS ARKIV: arkiv [at] obs-osv.com</p>
</br>
<p>Nettsiden er designet av Guttorm Guttormsgaard i samarbeid med Thomas Sørlie Hansen.</p>
<p>Mange av filmene og de fleste bildene er tatt av fotograf Silje Schild: siljeschild [at] gmail.com</p>
<p>Jorn-bildene er tatt av fotograf Anders Henriksen.</p>
<p>Filmene er laget av Harald Paalgard og Guttorm Guttormsgaard.</p>
<p>Gjenstandene er registrert av grafisk designer Anna Prestsæter: a.prestsaeter [at] gmail.com</p>
<p>CSS og design-input av grafisk designer Thomas Sørlie Hansen: post [at] thomashansen.no</p>
<p>Implementering av Django og Python-programmering av Kim-Tore Jensen: <a href="http://incendio.no">Incendio.no</a></p>
</br>
<p>For mer om ARKIVET og kommende utstillinger se Blaker Meieris hjemmeside: <a href="http://www.obs-osv.com/Blakerprosjektet.html">www.obs-osv.com</a>

</div>

  </header>

</div>

</body>
</html>

archive/templates/archive/feature_image.html
{% load thumbnail %}
{% load static %}
{% load media_thumb %}
	
<a href="{% if node %}{% url 'node_and_item' node_pk=node.pk pk=item.pk %}{% else %}{% url 'item' pk=item.pk %}{% endif %}">
	<div class="thumb ease">
		{% if num_macro > 0 %}<span class="icon makro-icon-{{ icon_color }}"></span>{% endif %}
		{% if num_movies > 0 %}<span class="icon{% if num_macro > 0 %}2{% endif %} film-icon-{{ icon_color }}"></span>{% endif %}
		{% if m %}
			<img src="{% media_thumb m 200 2000 %}" alt="{{ m }}" />
		{% else %}
			<img src="{% static "images/thumb_item.jpg" %}" alt="{{ item }}" />
			<p>{{ item }}</p>
		{% endif %}
	</div>
</a>

{# vi: se ft=htmldjango noet: #}

archive/templates/archive/filter_media.html
{% load thumbnail %}
{% load static %}
{% load media_thumb %}

<ul class="media_suggestion_matrix">
{% for m  in media %}
	<li>
		<a href="{{m.pk}}"><img src="{% media_thumb m 50 50 %}" style="height: 50px; width: 50px;" alt="{{m}}" />{{m}}</a>
	</li>	
{% endfor %}
</ul>

archive/templates/archive/item_detail.html
{% load i18n %}
{% load item_media %}

<!DOCTYPE HTML>
<html>
<head>
<meta charset=UTF-8>
<title>Guttormsgaards ARKIV</title>

<link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans:400,400italic,700,700italic' rel='stylesheet' type='text/css' />
<link rel="stylesheet" href="{{STATIC_URL}}css/style.css" type="text/css" />
<link rel="stylesheet" href="{{STATIC_URL}}css/jquery-ui-1.9.1.custom.min.css" type="text/css" />
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/mediaview.css" />

<!-- Internet Exploder needs a little push to get up in the morning. -->
<!--[if IE]>
	<script type="text/javascript" src="{{STATIC_URL}}js/excanvas.compiled.js"></script>
<![endif]-->

<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<script type="text/javascript" src="{{STATIC_URL}}js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/jquery-ui-1.9.1.custom.min.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/museum_functions.js"></script>

<script type="text/javascript" src="{{STATIC_URL}}js/fullscreen/jquery.fullscreen-min.js"></script>    
<script type="text/javascript" src="{{STATIC_URL}}js/mediaview/jquery.mousewheel.js"></script>    
<script type="text/javascript" src="{{STATIC_URL}}js/mediaview/jquery.mediaview.js"></script>    
<script type="text/javascript" src="{{STATIC_URL}}js/mediaview/mediaview.js"></script>    

</head>

<body>

	<div id="mediaview">

		<nav id="sidebar">	

			{% if node %}
				<a class="blocklink" href="{% url 'node' node_pk=current.pk %}">Tilbake</a>
			{% elif request.META.HTTP_REFERER %}
				<a class="blocklink" href="{{ request.META.HTTP_REFERER }}">Tilbake</a>
			{% else %}
				<a class="blocklink" href="/">Tilbake</a>
			{% endif %}

			<a class="blocklink" id="toggle-fullscreen" href="javascript:;">Fullskjerm</a>

			<a class="blocklink" id="toggle-details" href="javascript:;">Info</a>

			<div id="thumb-selector-container">
				<div id="scroll-up" class="blocklink">&#x25B2;</div>
				<div id="thumb-selector-inner">
					<div id="thumb-selector"></div>
				</div>
				<div id="scroll-down" class="blocklink">&#x25BC;</div>
			</div>

			{% comment %}
			<div id="thumb-navigator"></div>
			{% endcomment %}

		</nav>

		<div id="controls">
			<span id="zoom-in" aria-hidden="true" data-icon="&#x271a;"></span>
			<span id="zoom-out" aria-hidden="true" data-icon="&#x23bc;"></span>
			<span id="rotate" aria-hidden="true" data-icon="&#x2940;"></span>
			<span id="reset" aria-hidden="true" data-icon="&#x2715;"></span>
		</div>

		<div id="infobox">

		    <div id="infotext">

				<a href="#" class="toggle"><span aria-hidden="true" data-icon="&#x2715;"></span></a>

				{% if object.title %}
					<p>
						<span class="title">Tittel/betegnelse:</span>
						<span class="text">{{object.title}}</span>
					</p>
				{% endif %}

				{% if object.item_number %}
					<p>
						<span class="title">Reg.nr.:</span>
						<span class="text">{{object.item_number}}</span>
					</p>
				{% endif %}

				{% if object.artist %}
					<p>
						<span class="title">Kunstner/produsent:</span>
						<span class="text"><a href="{% url 'artist' artist=object.artist %}">{{object.artist}}</a></span>
					</p>
				{% endif %}

				{% if object.date_from or object.date_to %}
					<p>
						<span class="title">Datering:</span>
						<span class="text">
							{% if object.date_from %}
								{% if object.dating_certainty %}
									<span>{% if object.date_to %}Fra {% endif %}{% if object.dating_certainty != "sure" %}ca.{% endif %}</span> {{ object.date_from }}
								{% endif %}
								{% if object.era_from == "BC" and object.era_from != object.era_to %}
									{{ object.get_era_from_display }}
								{% endif %}
							{% endif %}
							{% if object.date_to %}
								{% if not object.date_from %}{{ object.date_to }}
								{% else %}
									<span>til</span> {{ object.date_to }}
								{% endif %}
								{% if object.era_to != object.era_from or object.era_to == "BC" %}
									{{ object.get_era_to_display }}
								{% endif %}
							{% endif %}
						</span>
					</p>
				{% endif %}

				{% if object.origin_city or object.origin_country %}
					<p>
						<span class="title">Opphavssted:</span>
						<span class="text">
						{% if object.origin_city %}
							<a href="{% url 'city' city=object.origin_city %}" />{{object.origin_city}}</a>
						{% endif %} 
						{%if object.origin_country %}
						{%if object.origin_city %}, {%endif%}
						<a href="{% url 'country' country=object.origin_country %}">{{ object.origin_country  }}</a>
						{% endif %} 
						 {% blocktrans %}{{ object.origin_certainty}}{% endblocktrans %}
						</span>
					</p>
				{% endif %}

				{% if object.dim_height or object.dim_width or object.dim_depth or object.dim_weight %}
					<p>
						<span class="title">Dimensjoner:</span>
						<span class="text">
							{% if object.dim_width %}
								<span style="text-transform: capitalize;">Bredde:</span> {{object.dim_width}} cm.
							{% endif %}
							{% if object.dim_height %}
								<span style="text-transform: capitalize;">Høyde:</span> {{object.dim_height}} cm.
							{% endif %}
							{% if object.dim_depth %}
								<span style="text-transform: capitalize;">Dybde:</span> {{object.dim_depth }} cm.
							{% endif %}
							{% if object.dim_weight %}
								<span style="text-transform: capitalize;">Vekt:</span> {{object.dim_weight }} cm.
							{% endif %}
						</span>
					</p>
				{% endif %}

				{% if object.materials.count > 0 %}
					<p>
						<span class="title">Materiale/teknikk:</span>
						<span class="text">{% for m in object.materials.all %}{{m}}{% if not forloop.last %},  {% endif%}{% endfor%}</span>
					</p>
				{% endif %}

				{% if object.origin_provinience %}
					<p>
						<span class="title">Proviniens:</span>
						<span class="text">{{object.origin_provinience|linebreaksbr}}</span>
					</p>
				{% endif %}

				{% if object.description %}
					<p>
						<span class="title">Beskrivelse:</span>
						<span class="text">{{object.description|linebreaksbr}}</span>
					</p>
				{% endif %}

				{% if object.ref_literature %}
					<p>
						<span class="title">Referanselitteratur:</span>
						<span class="text">{{object.ref_literature|linebreaksbr}}</span>
					</p>
				{% endif %}

			</div>

		</div>

		<div id="container">

			<ul>{% item_media object %}</ul>

		</div>

	</div>

	<script type="text/javascript" src="{{STATIC_URL}}js/functions.js"></script>
	
</body>

</html>

{# vi: se ft=htmldjango noet: #}